PROGRAM TESTIF
INTEGER VALOR
LOGICAL EHPOSITIVO
READ *, VALOR
EHPOSITIVO = VALOR .GT. 0
IF (EHPOSITIVO .AND. .TRUE.) THEN
    PRINT *, 'O valor e positivo'
ELSE
    PRINT *, 'O valor e negativo ou zero'
ENDIF
END